# Generated by Django 5.1.6 on 2025-03-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('chairs_counts', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
