# Generated by Django 5.1.6 on 2025-03-11 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.IntegerField(error_messages={'unique': 'Стол с таким номером уже существует!'}, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер стола')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('chairs_counts', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во стульев')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('is_available', models.BooleanField(default=True, verbose_name='Свободен')),
                ('is_maintenance', models.BooleanField(default=True, verbose_name='Обслуживает')),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
