# Generated by Django 5.1.6 on 2025-03-08 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='chairs_counts',
            field=models.IntegerField(default=1, verbose_name='Кол-во стульев'),
        ),
        migrations.AlterField(
            model_name='table',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.IntegerField(error_messages={'unique': 'Стол с таким номером уже существует!'}, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер стола'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
