# Generated by Django 5.1.6 on 2025-03-08 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_table_chairs_counts_alter_table_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='chairs_counts',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во стульев'),
        ),
    ]
