# Generated by Django 5.1.6 on 2025-03-08 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_table_chairs_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.IntegerField(error_messages={'unique': 'Стол с таким номером уже существует!'}, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер стола'),
        ),
    ]
