# Generated by Django 5.1.6 on 2025-03-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='description',
            field=models.CharField(max_length=1000, null=True, verbose_name='Описание'),
        ),
    ]
