# Generated by Django 5.1.6 on 2025-03-07 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('total_price', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'в ожидании'), ('COMPLETED', 'готово'), ('PAID', 'оплачено')], default='PENDING', max_length=9)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.table')),
            ],
        ),
    ]
